"""Pydantic schemas and enums shared across layers. Shapes only: no logic, no I/O."""

from src.common.schemas.actions import ApprovalRequest, CustomerDraft, OperationsNotification, RefundRecord
from src.common.schemas.decisions import Facts, GuardrailDecision, GuardrailResult, PolicyViolation, SeverityResult
from src.common.schemas.domain import Customer, Order, Subscription, SupportTicket
from src.common.schemas.enums import (
    ACTIVE_TICKET_STATUSES,
    ORDER_INTENTS,
    ActionName,
    ApprovalDecision,
    ApprovalStatus,
    Execution,
    GuardrailOutcome,
    Intent,
    IssueType,
    OrderStatus,
    RequestedAction,
    ResponseStatus,
    Risk,
    RuleId,
    Severity,
    SubscriptionPlan,
    SubscriptionStatus,
    TicketPriority,
    TicketStatus,
)
from src.common.schemas.ids import (
    CUSTOMER_ID_PATTERN,
    ORDER_ID_PATTERN,
    SUBSCRIPTION_ID_PATTERN,
    TICKET_ID_PATTERN,
    CustomerId,
    OrderId,
    SubscriptionId,
    TicketId,
)
from src.common.schemas.proposal import AgentProposal, ProposedAction
from src.common.schemas.response import AnalyzeResponse, ExecutedAction

__all__ = [
    "ACTIVE_TICKET_STATUSES",
    "CUSTOMER_ID_PATTERN",
    "ORDER_ID_PATTERN",
    "ORDER_INTENTS",
    "SUBSCRIPTION_ID_PATTERN",
    "TICKET_ID_PATTERN",
    "ActionName",
    "AgentProposal",
    "AnalyzeResponse",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalStatus",
    "Customer",
    "CustomerDraft",
    "CustomerId",
    "ExecutedAction",
    "Execution",
    "Facts",
    "GuardrailDecision",
    "GuardrailOutcome",
    "GuardrailResult",
    "Intent",
    "IssueType",
    "OperationsNotification",
    "Order",
    "OrderId",
    "OrderStatus",
    "PolicyViolation",
    "ProposedAction",
    "RefundRecord",
    "RequestedAction",
    "ResponseStatus",
    "Risk",
    "RuleId",
    "Severity",
    "SeverityResult",
    "Subscription",
    "SubscriptionId",
    "SubscriptionPlan",
    "SubscriptionStatus",
    "SupportTicket",
    "TicketId",
    "TicketPriority",
    "TicketStatus",
]
